# Generated by Django 4.2.7 on 2025-11-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_notification_chatmessage_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='dispute_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='employer_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='employer_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='worker_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='worker_signature',
            field=models.TextField(blank=True),
        ),
    ]
