# Generated by Django 4.2.7 on 2025-11-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_taskhistory_dispute_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='matcher.workerprofile'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='completed_successfully',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='employer_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='employer_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='worker_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='worker_signature',
            field=models.TextField(blank=True),
        ),
    ]
